# Generated by Django 4.0.4 on 2022-05-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_persona_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('Asistencia', models.CharField(max_length=100)),
                ('Comida', models.CharField(max_length=100)),
                ('Bebida', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tarea', models.CharField(max_length=100)),
                ('horario', models.IntegerField()),
                ('duracion', models.IntegerField()),
            ],
        ),
    ]
