# Generated by Django 4.0.4 on 2022-05-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0004_evento_tareas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Asistencia',
            new_name='asistencia',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='Bebida',
            new_name='bebida',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='Comida',
            new_name='comida',
        ),
    ]
